# Generated by Django 4.1.2 on 2022-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('producer', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
