# Generated by Django 4.1.2 on 2022-10-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_films_created_films_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
            ],
        ),
    ]
