# Generated by Django 4.1.2 on 2022-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ManyToManyField(blank=True, to='main.director'),
        ),
    ]
