# Generated by Django 4.1.2 on 2022-10-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_director_film_films_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='director',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
