# Generated by Django 4.1.2 on 2022-10-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_director_films_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='director',
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directors', to='main.director'),
        ),
    ]
